export type AppScreen =
  | "home"
  | "cards"
  | "add"
  | "env"
  | "goal"
  | "distribute"
  | "transactions"
  | "calendar"
  | "reports"
  | "imports"
  | "onboarding"
  | "reorder-envelopes"
  | "settings-accounts"
  | "settings-cards"
  | "settings-plan";
